### ISSUE TITLE
Constant random crashes & freezes - any suggestions what to do?

### ISSUE THREAD

**Issue by glowingkitty** [hellodeibu/gpd-pocket2-hackintosh#15]
I still get random crashes & freezes on a daily base - which makes macOS by far not as usable as it should be... does anyone have some suggestions (for example where I can find crash logs?) to help figuring out what is causing those crashes and how to fix them?
running 10.15.3 now, FileVaullt 2 enabled (and working, after I followed some tutorials and added some needed drivers).

**Comment by jibsaram** [comment]
(I'm going to go ahead and close this one too, same reason)
