### ISSUE TITLE
Switching from Clover to OpenCore?

### ISSUE THREAD

**Issue by glowingkitty** [hellodeibu/gpd-pocket2-hackintosh#16]
Has anyone ever worked with OpenCore? https://github.com/acidanthera/OpenCorePkg 
Could it possibly help making the GPD P2 hackintosh more stable?

**Comment by idchlife** [comment]
@glowingkitty how was you experience with hackintosh lately in gpd pocket 2? Is it stable enough to use on a daily basis or is it basically "ctrl-s everything every second because it may be the last"?

**Comment by glowingkitty** [comment]
Using my current Clover setup:
every once in a while I get a kernel panic that I cannot explain. But besides that, very stable and I could easily believe that I would use an actual macbook. Except for wifi and internal sound not working at the moment, which isn't an issue for me since I only use bluetooth speakers anyway.

Haven't tested OpenCore yet for my GPD Pocket 2, because I didn't see a good reason to switch now. But will take a look on OpenCore once I get my GPD Win Max:)

**Comment by idchlife** [comment]
@glowingkitty thank you for your information!

You mean wifi not working at all? You are connected with some kind of bluetooth modem?

**Comment by glowingkitty** [comment]
@idchlife internal wifi doesn't work. Which is typical for hackintosh. But you can always just connect a USB wifi stick to the GPD Pocket 2 and connect to wifi that way. Just make sure the stick has MacOS support.
