### ISSUE TITLE
Can't get bluetooth working

### ISSUE THREAD

**Issue by toto99303** [hellodeibu/gpd-pocket2-hackintosh#18]
Hello,

First of all thanks for all your hard work bringing this package to us!

I'd like to ask for help with troubleshooting the bluetooth.
I have installed Catalina and did all the fixes, etc, works great!
But I can't connect any bluetooth device (mouse).
When I open Bluetooth preferences it says "Bluetooth: On".
However no devices are detected. I tried with two different mouses and one keyboard.
Any help would be appreciated.

Thanks!

**Comment by jibsaram** [comment]
Apologies for my incredibly late reply, I've been out of the Hackintosh world for quite some time now, and somehow my Github notifications for this repository must've been disabled somehow. I hope you have resolved the issue by now or found a workaround, but if not, I'd recommend looking for a relevant Reddit or Discord community and asking for help there, I'm afraid I can't be of any use to you for this. Sorry about that.
