### ISSUE TITLE
Not Work GPD Pocket 2 Celeron 3965Y

### ISSUE THREAD

**Issue by WoolfDeveloper** [hellodeibu/gpd-pocket2-hackintosh#19]
Howdy!
I tried to install hackintosh with this clover project but this clover configuration reboot my GPD on the verbose.
I this guide unsupport GPD Pocket 2 Celeron 3965Y. 

That is why I am trying to configure hackintosh with OpenCore.
This is my repository: [GPD-pocket-2-hackintosh-open-core](https://github.com/WoolfDeveloper/GPD-pocket-2-hackintosh-open-core)

**Comment by jibsaram** [comment]
Apologies for the very late follow-up to this; my Github notifications were somehow turned off for this repository, no idea how that happened. Unfortunately I won't be able to help you as I've stopped using Hackintoshes and no longer have a Pocket 2. Even when I did I had the 8100Y variant, so things would've likely been different anyway. If you still face the issue, I'd advice looking for a relevant Reddit or Discord community and asking for help there. Sorry I can't be of more use. Good luck with everything, I hope you can get it to work! :)
