### ISSUE TITLE
One-Mix 3

### ISSUE THREAD

**Issue by balopez83** [hellodeibu/gpd-pocket2-hackintosh#2]
Hi, I see you have come a long way with getting macOS working on the GPD. I am attempting to do the same for the One-Mix 3 from One-Netbook which is basically the same device and same specs except with the ssd built in. I have attempted to utilize your clover folder which has been a big help getting me closer though since a new DSDT file is required for the One-Mix I wanted to ask you what patches you used when you created your file. Since the One-Mix uses the exact same graphics and processor chip I was wondering if you could provide a list or attach the patches you used to get graphics fully functional as well as battery indicator? I think this will be the last piece to finally getting full graphics support. Thank you in advance, and great job getting this functional for the GPD

**Comment by gymnae** [comment]
Were you able to boot from USB and install it? 
I'm stuck at that stage. It stalls without giving a KP or some other timeout, almost as if it cannot read the HFS+ partioned usb stick. This was never a problem with other hackintosh attempts.

**Comment by balopez83** [comment]
Hi @Gymnae, yes I had problems as well and realized I had a couple issues; 

I just want to confirm that your issue is related to the One-Mix Yoga 2s/3/3s? I do not know if the GPD Pocket 2 has the same issues though it uses the exact same hardware and UEFI with the exception of the SSD so I suspect it will work for that as well.

1) make sure you use a USB 2.0 drive to install and not 3.0. The current kexts and config file for some reason do not support the USB A port in 3.0 mode only 2.0. I haven't figured out the solution yet but have some ideas how to solve it. If you don't have a USB 2.0 drive you could also try a USB 2.0 hub or use a USB A to USB-C adapter and that seems to work too. 

2)You will need to remove all intel video settings from the config file as it seems to cause an issue with the installer boot process. I am attaching a zipped EFI that worked to boot my installer from USB.  
[EFI.zip](https://github.com/hellodeibu/gpd-pocket2-hackintosh/files/3454112/EFI.zip)

**Comment by balopez83** [comment]
@Gymnae , if you boot your installer in verbose mode and disable restart on KP and post an image of the screen where it hangs I may be able to give you an idea of the issue and how to solve it, assuming the above options don't work.

**Comment by balopez83** [comment]
Hi @Gymnae , I created a GitHub repository with an EFI that is getting close to full function on the One-Mix 3 and likely will work on the 2s. I have also been able to get full graphics acceleration working for macOS Sierra (yes I know its older) and am working on Mojave and Catalina now. Hope this helps and if you can help with any of the issues listed on my page I would appreciate it. Here is the link
[https://github.com/balopez83/One-Mix-3-Hackintosh](url)

**Comment by gymnae** [comment]
@balopez83, thanks for linking to your repo. 
I'll be watching your repo, right now I'm too low on time to fiddle with mojave or catalina. Seems promising what you are doing so far.
At the moment I'm actually not too unhappy with Manjaro Linux Cinnamon.

**Comment by jibsaram** [comment]
@balopez83 This is fantastic! I've [added a note and a link](https://github.com/hellodeibu/gpd-pocket2-hackintosh#note-for-one-mix-devices) to your efforts in case any other One Mix device owners find my repository. Cheers!
