### ISSUE TITLE
Internal Graphic issue for 8100y

### ISSUE THREAD

**Issue by clams92** [hellodeibu/gpd-pocket2-hackintosh#21]
I have a UHD 615. Fonts are broken and macOS Utilities do not appear.

**Comment by jibsaram** [comment]
I'm afraid I no longer use Hackintoshes nor do I have the Pocket 2, so I can't help you with this. I'd suggest finding a relevant Reddit or Discord community and asking for help there -- or consider re-installing the necessary kexts, following the guidance in this repo as closely as you can.

Sorry I can't be of more help. Good luck, I hope you can get it to work!
