### ISSUE TITLE
Update VoodooI2CGoodix to 0.4.0 to fix double click, right click issues

### ISSUE THREAD

**Issue by lazd** [hellodeibu/gpd-pocket2-hackintosh#22]
Howdy, VoodooI2C Goodix 0.4.0 was recently released, including double click support, better right click support, and less phantom releases while dragging. It's a joy to use an feels much more natural.

Please update the kext you ship, test, and report back if it works!

https://github.com/lazd/VoodooI2CGoodix/releases/tag/v0.4.0

**Comment by jibsaram** [comment]
That's awesome, fantastic work! Unfortunately I don't have the GPD Pocket 2 anymore, so I can't actually test or use this myself. I'd be happy to accept a PR with necessary changes though, for anyone who has a Pocket 2 and wants to Hackintosh it. @THEDEVIOUS1 might also be interested for their work for the Chuwi Minibook over at https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH, and perhaps some/all of the One devices too (I'm not sure what touch screen they use).

**Comment by lazd** [comment]
Thanks @jibsaramnim, I actually developed this kext with @THEDEVIOUS1's help, and I have tested it on the MiniBook. It works great. These updates do not require extensive testing, rather you just simply need to update the kext in your repo. I could send a PR if that makes it easier, but I figured I'd reach out just in case.

**Comment by jibsaram** [comment]
Ah, that makes sense! And that'd be absolutely great yes! Actually, Thedevious has access to this repository too, they've been managing it pretty much fully as I've not had a Pocket 2 in a few years now :).

**Comment by jibsaram** [comment]
I've just gone ahead and created a PR. If this looks alright to you or if I missed anything, please let me know. And thanks so much once again!

**Comment by THEDEVIOUS1** [comment]
@lazd & @jibsaramnim 
great to know that both of you guys are doing good...since i see you have been active on here just wanted to jump on the opportunity to make a major update to the repo. it seems that thanks to [emeraldsdhc.kext](https://github.com/acidanthera/EmeraldSDHC) we may FINALLY have internal emmc support for...the problem now is that none of still own the device to test it. With that said though...i started a reddit thread when i switch to opencore a few months back so hopefully i can find a fellow or 2 from there to try it out and get it going

**Comment by jibsaram** [comment]
Wow, that'd certainly be fantastic news for those who still want to keep thet Macbook Nano alive!

Though at this point, hardware availability is a bit of a challenge too. With Chuwi all but out of this business too, and GPD having fully embraced the high-end/enthusiast corner instead, for devices of this size and budget we really only have "no brand" options or second hand sales left. Something like the [Topton 7" w/ J4105](https://www.aliexpress.com/item/1005002768113019.html) is all that's left. I have no idea what kind of build quality or compatibility you can expect of these though, but at least Topton is a relatively known name in the small PC / custom network router market.

Please feel free to open up a new issue or so if anything comes out of this new effort! :)
