### ISSUE TITLE
did anyone ever manage to try to run on 3965y?

### ISSUE THREAD

**Issue by murkomarko** [hellodeibu/gpd-pocket2-hackintosh#25]
just wondering if its worth to waste my time

**Comment by jibsaram** [comment]
I have not no, as I never had that particular model. I am not sure if anyone else tried this. Sorry I can't be of more help, but if you do end up trying, please by all means let us know if you managed to get this working :)

**Comment by murkomarko** [comment]
> I have not no, as I never had that particular model. I am not sure if anyone else tried this. Sorry I can't be of more help, but if you do end up trying, please by all means let us know if you managed to get this working :)

it seems to be impossible to install macos on mobile celeron devices actually
