### ISSUE TITLE
DSDT patch question

### ISSUE THREAD

**Issue by balopez83** [hellodeibu/gpd-pocket2-hackintosh#5]
Hi, sorry to post this in the issue section but I am really trying to figure out what patches you used to get the battery status working among other things. Your DSDT patch actually works for the OneMix 3 but for me to fix other issues with that computer I will have to make a custom specifically for that computer. Can you provide all your patches so I can integrate them into a specific DSDT for the OneMix? Unfortunately I’m not as skilled yet with creating the patches so any help you can provide would be greatly appreciated. Thank you again for all the work you did here, without it I doubt I would have gotten as far.

**Comment by jibsaram** [comment]
Hi! Apologies for the belated reply, GitHub seems to never actually notify me of new issues being posted.

Unfortunately I can't remember the specifics of what I did. What I do remember is that there was a conversion I needed to do as macOS expects battery data in a certain type, whereas on certain devices (like the Pocket 2) it was provided in another type. I can't for the life of me remember what it was, but it was either 32bit but expected 16bit, or 16bit but expected 8bit. Something along those lines. I ended up searching for guides online on how to make the battery status work and after following it to the letter I was able to get it to work (or, at least it looks that way).

I'm sorry I can't be of more help. Unfortunately I don't have the Pocket 2 anymore so I can't continue to complete this project. My hope is that others such as yourself with these kinds of devices will continue and share their results publicly, either by submitting pull requests or by sharing their own repositories. I wish I could be of more help.

**Comment by lazd** [comment]
@hellodeibu sold the Pocket 2? Did you replace it with anything similar?

**Comment by jibsaram** [comment]
> @hellodeibu sold the Pocket 2? Did you replace it with anything similar?

I did yes, I needed the funds. Unfortunately right now I don't have a replacement. I'd love to get a similar device again one day (especially to Hackintosh it), but for now I'm simply not able to do this.

**Comment by lazd** [comment]
@hellodeibu dang, I hope you're able to get something soon to achieve your MacBook Nano dream :)

I am looking at the OneMix 2S or 3S (and @balopez83's [repo](https://github.com/balopez83/One-Mix-3-Hackintosh)). There's also the Chuwi MiniBook 8, but I haven't found anyone having luck with those yet.

**Comment by jibsaram** [comment]
I hope so too! The OneMix 2/3s certainly looks interesting yes. I'm very happy to see multiple companies producing products in this little niche of a corner. So long as they keep trying to innovate and improve upon the concept, it's only a good thing for us consumers. The GPD P2 Max is quite a good looking choice too, for those who want something with an almost full-sized keyboard that is still very portable, but I'll always have a weak spot for true pocketable devices :).
