### ISSUE TITLE
Built-in SD Reader is actually working? 

### ISSUE THREAD

**Issue by pokemonerdotcom** [hellodeibu/gpd-pocket2-hackintosh#6]
I don't have GPD Pocket 2 butI'm using One Mix 3s when I followed Balopez83's tutorial to install Hackintosh. But I actually search on google about built-in SD Reader on Hackintosh but I don't see any way to fix it. Hmm, some topics can detect it but it isn't working! Anyway, If it can work on your GPD pocket 2 so how you can do that. I actually checked on your EFI but I think you don't patch SSDT! Thank you for reading!

**Comment by daveschz** [comment]
I'm a noob at Hackintosh and I don't have the MicroSD working on my build. It's not the end of the world but I'd love to know how to fix it. Edit: I'm on a GPD Pocket 2 running the OS off a thumb drive.

**Comment by zanjie1999** [comment]
GPD Pocket 2 use a usb3.0 card reader for built-in tf card reader, so,  is working like a usb driver, but One Mix 3s use intel cpu sdio for built-in tf card reader, mac os has no sido driver for intel cpu, so, not working(like emmc for GPD Pocket 2).
