### ISSUE TITLE
Markdown info: WiFi & external displays working?

### ISSUE THREAD

**Issue by glowingkitty** [hellodeibu/gpd-pocket2-hackintosh#7]
Is WiFi working? If not - any chance it will in the near future?
And how about external displays via USB-C/ USB-C to HDMI adapters?

**Comment by daveschz** [comment]
The built in wifi is not working, and AFAIK never will. Apple just has a very limited support for wifi hardware. I bought an external USB wifi adapter though and that works. It uses its own driver compiled for Mac.

Both of the options for external displays did work, with caveats. I just have a limited understanding of Hackintosh, so if you do too you'll probably be in the same boat. My HDMI wouldn't display, as 1920 x 1200 is out of its display resolution, and I didn't have options for 1080p. I probably just need to add more resolutions to my config.plist or something. I did also use an AOC USB-C display that I have, and it worked, but same issue with resolution. It was stretched and didn't have options for me to adjust the resolution.

**Comment by glowingkitty** [comment]
thanks @daveschz :) was considering using a gpd pocket 2 hackintosh in combination with one of those 4K USB-C portable displays - and wondering if that would work out. Also... do you know if Catalina also works fine with the current configuration?
